[package]
name = "rust-import"
version = "0.1.0"
authors = ["Weder Sousa <weder.sousa@squadra.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
